name: Package VS Code Extension

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Package extension
        id: package
        uses: nhedger/package-vscode-extension@v1

      - name: Publish extension artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.package.outputs.packagePath }}
