name: Package VS Code Extension

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Package extension
        id: package
        uses: nhedger/package-vscode-extension@v1

      - name: Get package data
        id: packageData
        run: |
          echo "name=$(cat package.json | jq '.name' | tr -d '"')" >> $GITHUB_OUTPUT
          echo "version=$(cat package.json | jq '.version' | tr -d '"')" >> $GITHUB_OUTPUT

      - name: Publish extension artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.packageData.outputs.name }}-${{ steps.packageData.outputs.version }}.vsix
          path: ${{ steps.package.outputs.packagePath }}
